### ISSUE TITLE
Apollo API "help screen" pops up every time you swipe away from an image

### ISSUE THREAD

**Issue by cquick01** [ryannair05/ApolloAPI#10]
Each time I have an image open fullscreen in Apollo, then swipe it away, this screen pops up. Kinda annoying having to close it each time... It doesn't seem to happen with text posts, or images that aren't opened fullscreen.

![image](https://github.com/ryannair05/ApolloAPI/assets/72400253/590c9f23-c552-4f38-acc1-75d7a284e19c)

**Comment by ryannair05** [comment]
Fixed in version 1.0.1
