### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by stevehoek** [ryannair05/ApolloAPI#6]
On a Mac with Xcode... make in the ApolloAPI folder doesn't succeed.  no Xcode project.  Any tips?

**Comment by CaptainCoble** [comment]
If not jailbroken, use [this](https://www.reddit.com/user/megajigglypuff7I4/comments/1485ygz/how_to_add_personal_api_key_to_apollo/) to inject the tweak into the Apollo app.
download Apollo 1.15.11 for the last working version. 
Skip step 4 of setup. 
Sideload via sideloadly or altstore or whatever you want.  
Worked for me on 16.5.1 with Apollo 1.15.11
You will have to reinject the tweak and sideload again with every update.

**Comment by ryannair05** [comment]
[Theos](https://theos.dev) is required to build. With Theos installed run `make package` in the project's directory to build ApolloAPI. If you would like to install through SSH, you can run `make install` to install the tweak to a jailbroken device through SSH with `THEOS_DEVICE_IP` set to the device's IP address. I have added a ReadMe to this project with basic building instructions
